### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by ChrisBeeley** [The-Strategy-Unit/visualising-inequalities#5]
Are the funders happy with an open licence? Happy to advise on this if they are

**Comment by Lextuga007** [comment]
A good question and whilst I think this particular code is debatably owned by this one project (as it was from elsewhere) @jacgrout is hoping to release code for the main output so worth confirming.

To create a licence @jacgrout I use `usethis::use_mit_license()` to create the licence but as this is an open licence, Chris' point about checking there are no objections needs to happen first 🙂

**Comment by jacgrout** [comment]
We have permission for the code to be publically available via Github

**Comment by ChrisBeeley** [comment]
Great news. I would recommend adding them as the copyright holder and adding an MIT licence. Zoë/ I can help
